# on:
#   push:
#     tags:
#       - 'v*'

# name: Create Release

# jobs:
#   build:
#     name: Create Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@master
#       - name: Create Release for Tag
#         id: create_release
#         uses: Hongbusi/create-release@main
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ github.ref }}
